"""Auto-generated figure-label glossary (English -> Simplified Chinese).

Long-tail figure axis/title/legend labels translated in one batch via Gemini
(gemini-2.5-flash-lite) and spot-reviewed, then merged into _FIG_GLOSSARY in
core.py (used by the savefig label localizer). Whole-label entries, matched
longest-first so they win over component-word fallbacks; acronyms/symbols/units
are kept in English. Hand-curated entries in core.py take precedence on key clash.
"""

from __future__ import annotations

EXTRA: dict[str, str] = {
    "% Contribution": "% 贡献",
    "% Study Var": "% 研究变量",
    "% of model R²": "% 模型R²",
    "-log10(PH test p-value)": "-log10(PH检验p值)",
    "0.05 significance": "0.05显著性",
    "1 - Specificity (FPR)": "1 - 特异度 (FPR)",
    "1 per row": "每行1个",
    "1-factor loading (lambda)": "1因子载荷 (lambda)",
    "2-group DiD (switchers vs stable)": "2组DiD (转换者 vs 稳定者)",
    "2SLS coefficient (95% CI; red = endogenous, IV-identified)": "2SLS系数 (95% CI; 红色 = 内生变量, IV识别)",
    "2x2 DiD estimate": "2x2 DiD估计量",
    "94% credible band": "94% 可信区间",
    "94% forecast band": "94% 预测区间",
    "94% level band": "94% 水平区间",
    "95% predictive band": "95% 预测区间",
    "Ability (theta)": "能力 (theta)",
    "Alpha-if-item-dropped (red = removal RAISES alpha)": "删除项后的Alpha (红色 = 删除提高alpha)",
    "Association measures (forest)": "关联度量 (森林图)",
    "BIC (lower = better)": "BIC (越低越好)",
    "BIC (lower is better)": "BIC (越低越好)",
    "BIC by k": "按k分组的BIC",
    "Bayesian A/B test — Beta posteriors": "贝叶斯A/B测试 — Beta后验分布",
    "Bayesian Poisson rate — Gamma posterior": "贝叶斯泊松率 — Gamma后验分布",
    "Bayesian proportion — Beta posterior": "贝叶斯比例 — Beta后验分布",
    "Bland-Altman agreement plot": "Bland-Altman一致性图",
    "Blundell-Bond system GMM": "Blundell-Bond系统GMM",
    "Brant test: per-predictor slopes across cut points": "Brant检验：跨分界点的每预测变量斜率",
    "Bray-Curtis dissimilarity": "Bray-Curtis不相似度",
    "CATE distribution (heterogeneous effects)": "CATE分布 (异质性效应)",
    "CE frontier": "CE前沿",
    "Callaway & Sant'Anna (2021) — dynamic ATT (event study)": "Callaway & Sant'Anna (2021) — 动态ATT (事件研究)",
    "Category boundary on ability (theta)": "能力 (theta)上的类别边界",
    "Cointegrating residual (ECT) — mean-reverting if cointegrated": "协整残差 (ECT) — 协整时均值回复",
    "Columns": "列",
    "Conditional logit: attribute coefficients": "条件Logit：属性系数",
    "Conversion rate": "转化率",
    "Cost-Volume-Profit (break-even) analysis": "成本-销量-利润 (盈亏平衡) 分析",
    "Count component (log-rate)": "计数分量 (对数率)",
    "Cronbach's alpha if item dropped": "删除项后的Cronbach's alpha",
    "Cumulative Incidence Functions (Aalen-Johansen)": "累积发生函数 (Aalen-Johansen)",
    "Customer Lifetime Value distribution": "客户生命周期价值分布",
    "Dim 1": "维度 1",
    "Dim 2": "维度 2",
    "Discordant pair count": "不一致配对计数",
    "Duane / Crow-AMSAA reliability-growth plot": "Duane / Crow-AMSAA可靠性增长图",
    "Dynamic panel GMM (Arellano-Bond)": "动态面板GMM (Arellano-Bond)",
    "E-value (RR scale)": "E值 (RR尺度)",
    "EFA loadings": "EFA载荷",
    "Emergy by source (R / N / F)": "能源按来源 (R / N / F)",
    "Event study (dynamic treatment effects)": "事件研究 (动态处理效应)",
    "FE (fixed effects)": "FE (固定效应)",
    "Flow-Duration Curve (Weibull plotting positions)": "流量-持续时间曲线 (Weibull绘图位置)",
    "Friedman's H (0=no interaction, 1=pure interaction)": "Friedman's H (0=无交互, 1=纯交互)",
    "GARCH(1,1) conditional volatility": "GARCH(1,1) 条件波动率",
    "GMM coefficient (95% CI)": "GMM系数 (95% CI)",
    "GMM model selection by BIC": "GMM模型选择 (按BIC)",
    "GP mean": "GP均值",
    "GP predicted mean": "GP预测均值",
    "Gamma (hidden-bias magnitude)": "Gamma (隐藏偏差幅度)",
    "Gaussian-process regression: posterior mean + 95% band": "高斯过程回归：后验均值 + 95%区间",
    "General dominance (avg incremental R²)": "一般优势 (平均增量R²)",
    "Goodman-Bacon (2021) decomposition of TWFE DiD": "Goodman-Bacon (2021) TWFE DiD分解",
    "Goodman-Bacon weight": "Goodman-Bacon权重",
    "Granger causality  -log10(p)": "Granger因果关系 -log10(p)",
    "HT coefficient (95% CI; red = time-invariant)": "HT系数 (95% CI; 红色 = 时间不变)",
    "Hausman test: FE vs RE coefficients": "Hausman检验：FE vs RE系数",
    "Hausman-Taylor estimator": "Hausman-Taylor估计量",
    "Hill alpha-hat(k)  (tail index = 1/alpha)": "Hill alpha-hat(k) (尾部指数 = 1/alpha)",
    "Historical CLV (total monetary per customer)": "历史CLV (每客户总货币价值)",
    "Honest DiD (Rambachan-Roth 2023) — sensitivity to parallel-trends violations": "Honest DiD (Rambachan-Roth 2023) — 对平行趋势违反的敏感性",
    "I (infected)": "I (感染)",
    "IndVal (specificity x fidelity x 100)": "IndVal (特异度 x 保真度 x 100)",
    "Indicator species (red: p<0.05)": "指示物种 (红色: p<0.05)",
    "Indirect effect of X on Y via M": "X对Y通过M的间接效应",
    "Individuals (I) chart": "个体 (I) 图",
    "Influence plot (point size proportional to Cook's D)": "影响图 (点大小与 Cook's D 成正比)",
    "Instrumental variables (2SLS)": "工具变量 (2SLS)",
    "Intensity-Duration-Frequency (IDF) curve": "强度-持续时间-频率 (IDF) 曲线",
    "Interrupted time series (segmented regression)": "中断时间序列 (分段回归)",
    "Intraclass correlation forms (Shrout & Fleiss 1979)": "组内相关系数形式 (Shrout & Fleiss 1979)",
    "Johnson-Neyman: conditional effect vs moderator": "Johnson-Neyman: 条件效应 vs 调节变量",
    "Join counts: observed vs expected (free sampling)": "连接计数: 观测值 vs 期望值 (自由抽样)",
    "Kaiser (eigenvalue=1)": "Kaiser (特征值=1)",
    "Kaplan-Meier survival": "Kaplan-Meier 生存",
    "Kriging variance (uncertainty)": "Kriging 方差 (不确定性)",
    "LCA — item-response profiles by class": "LCA — 按类别划分的项目反应剖面",
    "LDA top words per topic": "LDA 每个主题的 top 词",
    "LPA — class mean profiles (standardized)": "LPA — 类别均值剖面 (标准化)",
    "Leontief output multipliers & linkages": "Leontief 产出乘数与联系",
    "Ljung-Box p-value": "Ljung-Box p 值",
    "MDS dim 1": "MDS 维度 1",
    "MDS dim 2": "MDS 维度 2",
    "MH delta-DIF  (-=favours focal, +=favours reference)": "MH delta-DIF (-=偏向目标项, +=偏向参考项)",
    "Malmquist TFP index (>1 = growth)": "Malmquist TFP 指数 (>1 = 增长)",
    "Material flow Sankey: inputs -> system -> outputs + stock": "物料流桑基图: 输入 -> 系统 -> 输出 + 库存",
    "Material flow balance: inputs = outputs + net stock addition": "物料流平衡: 输入 = 输出 + 净库存增量",
    "Mbar (relative-magnitudes bound on post vs max pre violation)": "Mbar (后验 vs 最大先验违反的相对幅度界限)",
    "Mean predicted probability": "平均预测概率",
    "Mean-excess plot (linear -> GPD tail)": "平均超额图 (线性 -> GPD 尾部)",
    "Mendelian randomization": "孟德尔随机化",
    "Missingness map (dark = missing)": "缺失图 (深色 = 缺失)",
    "Moderated moderation (model 3): X effect by W, Z": "调节的调节 (模型 3): X 对 W, Z 的效应",
    "Moran scatterplot": "Moran 散点图",
    "Moving-range (MR) chart": "移动极差 (MR) 图",
    "Mundlak CRE: within (beta) vs entity-mean (gamma)": "Mundlak CRE: 组内 (beta) vs 实体均值 (gamma)",
    "OLS fit": "OLS 拟合",
    "Observed frequency": "观测频率",
    "Occupancy probability": "占用概率",
    "Odds ratio (log scale)": "优势比 (对数尺度)",
    "Ordered probit: latent-scale coefficients": "有序概率模型: 潜变量尺度系数",
    "Oster (2019) coefficient stability": "Oster (2019) 系数稳定性",
    "P(correct)": "P(正确)",
    "P(item = 1 | class)": "P(项目 = 1 | 类别)",
    "P1 payoff": "P1 收益",
    "P1 strategy (row)": "P1 策略 (行)",
    "P2 strategy (column)": "P2 策略 (列)",
    "PC CPDAG adjacency (1 = edge source->target)": "PC CPDAG 邻接 (1 = 边源->目标)",
    "PCA scree plot": "PCA 碎石图",
    "PV benefit": "PV 效益",
    "PV cost": "PV 成本",
    "PV output": "PV 输出",
    "Parallel mediation (model 4)": "平行中介 (模型 4)",
    "Partial correlation: residual vs residual": "偏相关：残差 vs 残差",
    "Pearson scatter with OLS fit": "Pearson 散点图 (OLS 拟合)",
    "Propensity overlap (AIPW positivity)": "倾向重叠 (AIPW 阳性)",
    "Propensity overlap (IPW positivity)": "倾向重叠 (IPW 阳性)",
    "Propensity overlap (common support)": "倾向重叠 (共同支持)",
    "Proportion (theta)": "比例 (theta)",
    "Proportional-hazards test (scaled Schoenfeld, rank)": "比例风险检验 (缩放 Schoenfeld, rank)",
    "Proportional-odds ordinal logit: odds ratios": "比例优势序数 Logit：优势比",
    "R (recovered)": "R (恢复)",
    "R chart": "R 控制图",
    "RCBD treatment means": "RCBD 处理均值",
    "RE (random effects)": "RE (随机效应)",
    "RFM segment": "RFM 细分",
    "RFM segment sizes": "RFM 细分大小",
    "RMST: KM curves with restricted area up to tau": "RMST：KM 曲线 (区域限制至 tau)",
    "ROC curve": "ROC 曲线",
    "Rate (lambda)": "率 (lambda)",
    "Return distribution with VaR thresholds (losses on left)": "收益分布 (VaR 阈值, 损失在左)",
    "Ripley's L (centred) with CSR envelope": "Ripley's L (中心化) (CSR 包络)",
    "Robust (MCD) Mahalanobis outlier detection": "稳健 (MCD) Mahalanobis 离群点检测",
    "Rosenbaum sensitivity bounds (signed-rank)": "Rosenbaum 敏感性界限 (符号秩)",
    "Rows": "行",
    "S (susceptible)": "S (易感)",
    "SEM coefficient (95% CI)": "SEM 系数 (95% CI)",
    "SEM measurement loadings": "SEM 测量载荷",
    "SFA technical-efficiency distribution": "SFA 技术效率分布",
    "SNP -> exposure effect": "SNP -> 暴露效应",
    "SNP -> outcome effect": "SNP -> 结果效应",
    "Sensitivity (TPR)": "灵敏度 (TPR)",
    "Serial mediation (model 6)": "序列中介 (模型 6)",
    "Shapley value": "Shapley 值",
    "Split-plot interaction (A × B)": "裂区交互作用 (A × B)",
    "Staggered DiD — Sun-Abraham interaction-weighted ATT": "交错 DiD — Sun-Abraham 交互作用加权 ATT",
    "Standardized Pearson residuals (O-E)/sqrt(E)": "标准化 Pearson 残差 (O-E)/sqrt(E)",
    "System-GMM coefficient (95% CI)": "系统 GMM 系数 (95% CI)",
    "TOPSIS closeness score": "TOPSIS 贴近度得分",
    "Texture class distribution": "纹理类别分布",
    "Theta forecast": "Theta 预测",
    "Top association rules by lift": "按 lift 排名的关联规则",
    "U1 (X canonical variate)": "U1 (X 典型变量)",
    "USDA soil texture triangle": "USDA 土壤质地三角图",
    "Unique": "唯一",
    "Unique variance (R² contribution)": "唯一方差 (R² 贡献)",
    "Unweighted vs design-weighted mean (95% CI)": "未加权与设计加权均值 (95% CI)",
    "V1 (Y canonical variate)": "V1 (Y 典型变量)",
    "VIF (capped at 50 for display)": "VIF (显示上限为 50)",
    "VIF = 10 (severe)": "VIF = 10 (严重)",
    "VIF = 5 (moderate)": "VIF = 5 (中度)",
    "VanderWeele-Ding (2017) E-value": "VanderWeele-Ding (2017) E 值",
    "Variance Inflation Factor per predictor": "每个预测变量的方差膨胀因子",
    "Weibull probability plot": "Weibull 概率图",
    "activity (sorted by contribution)": "活动 (按贡献排序)",
    "actual (green=covered)": "实际 (绿色=覆盖)",
    "actual (held-out)": "实际 (保留)",
    "after (raked)": "之后 (加权)",
    "age x": "年龄 x",
    "age-to-age factor f_j": "年龄间因子 f_j",
    "annual cost": "年成本",
    "backward linkage": "向后链接",
    "before (base)": "之前 (基线)",
    "beta (within)": "beta (内部)",
    "bounding p-value (one-sided)": "边界 p 值 (单侧)",
    "cash flow": "现金流",
    "cash flow / cumulative PV": "现金流 / 累计现值",
    "caused →": "导致 →",
    "causing →": "引起 →",
    "censored": "删失",
    "chance": "机会",
    "class (jittered)": "类别 (抖动)",
    "coefficient (95% CI)": "系数 (95% CI)",
    "coefficient (latent-normal scale, 95% CI)": "系数 (潜在正态尺度, 95% CI)",
    "columns": "列",
    "condition": "条件",
    "condition mean ±95% within-subj CI": "条件均值 ±95% 被试内 CI",
    "conditional indirect effect": "条件间接效应",
    "conditional volatility σ_t": "条件波动率 σ_t",
    "conditional-logit coefficient beta (95% CI)": "条件 Logit 系数 beta (95% CI)",
    "consecutive period pair": "连续周期对",
    "cost / revenue": "成本 / 收入",
    "count-model coefficient (95% CI)": "计数模型系数 (95% CI)",
    "counterfactual": "反事实",
    "critical ratio CR = Cu/(Cu+Co)": "临界比 CR = Cu/(Cu+Co)",
    "cross-validated R2": "交叉验证 R2",
    "cumulative MTBF (log)": "累计 MTBF (log)",
    "cumulative discounted CF": "累计折现 CF",
    "cumulative incidence": "累计发生率",
    "cumulative probability": "累计概率",
    "cumulative test time (log)": "累计测试时间 (log)",
    "cumulative wealth (1+r) compounded": "累计财富 (1+r) 复利",
    "cut point k  (binary logit of 1[y > level_k])": "切点 k (二元 Logit 的 1[y > level_k])",
    "data": "数据",
    "data (density)": "数据 (密度)",
    "design points": "设计点",
    "development period transition": "开发期过渡",
    "direct": "直接",
    "documents": "文档",
    "drawdown": "回撤",
    "duration (log scale)": "持续时间 (log 尺度)",
    "edge probability": "边概率",
    "effect (95% CI)": "效应 (95% CI)",
    "effect estimate with 95% CI": "效应估计与 95% CI",
    "effect size (Cohen's f)": "效应量 (Cohen's f)",
    "eigenvalue": "特征值",
    "embedding distance": "嵌入距离",
    "emergy (sej)": "能量 (sej)",
    "empirical CDF": "经验 CDF",
    "environment": "环境",
    "environmental/spatial distance (euclidean)": "环境/空间距离 (欧几里得)",
    "equilibrium error": "均衡误差",
    "estimated population size N": "估计种群大小 N",
    "estimated propensity e(X)": "估计倾向 e(X)",
    "estimated slope": "估计斜率",
    "estimated species richness": "估计物种丰富度",
    "event time (relative to onset; ref = -1)": "事件时间 (相对于发作; ref = -1)",
    "event time e (length of exposure; pre e<0 should hover near 0)": "事件时间 e (暴露长度; e<0 时应接近 0)",
    "exceedance probability (%)": "超额概率 (%)",
    "excess = loss - u": "超额 = 损失 - u",
    "excesses": "超额",
    "expected (CSR)": "期望 (CSR)",
    "expected richness E[S]": "期望丰富度 E[S]",
    "explained variance ratio": "解释方差比",
    "externally studentized residual": "外部学生化残差",
    "extracted common factor (sign-fixed)": "提取的公因子 (符号固定)",
    "failures": "失败",
    "failures (median rank)": "失败 (中位数秩)",
    "fitted normal": "拟合正态",
    "footprint": "足迹",
    "forecast": "预测",
    "forward linkage": "前向联系",
    "gamma (entity mean)": "gamma (实体均值)",
    "genotype": "基因型",
    "global transitivity": "全局传递性",
    "hazard ratio exp(coef) (log scale, 95% CI)": "风险比 exp(coef) (log 尺度, 95% CI)",
    "holding cost Q/2*H": "持有成本 Q/2*H",
    "impact on outcome": "对结果的影响",
    "indirect (spillover)": "间接 (溢出)",
    "indirect effect (95% boot CI)": "间接效应 (95% boot CI)",
    "individual": "个体",
    "individual value": "个体值",
    "information criterion (lower = better)": "信息准则 (越低越好)",
    "inlier": "内点",
    "instruments": "工具变量",
    "intensity (log scale)": "强度 (对数尺度)",
    "join count": "连接计数",
    "k-distance elbow (eps heuristic)": "k-距离肘部 (eps启发式)",
    "kriging variance": "克里金方差",
    "level (posterior mean)": "水平 (后验均值)",
    "leverage (hat diag)": "杠杆 (hat diag)",
    "life (log)": "寿命 (log)",
    "life expectancy e_x": "预期寿命 e_x",
    "lift = 1 (independence)": "提升度 = 1 (独立性)",
    "ln(time-to-failure)": "ln(失效时间)",
    "local R^2": "局部 R^2",
    "log(R/S) observed": "log(R/S) 观测值",
    "log(window size)": "log(窗口大小)",
    "loss amount": "损失金额",
    "loss data": "损失数据",
    "lower-bound p": "下界 p",
    "mass flow (consistent unit, e.g. tonnes)": "质量流 (一致单位, e.g. 吨)",
    "mean TF-IDF": "平均 TF-IDF",
    "mean excess e(v)": "平均超额 e(v)",
    "mean rank": "平均排名",
    "mean(|SHAP value|)": "平均(|SHAP值|)",
    "measurement": "测量值",
    "median pred": "中位数预测值",
    "mode": "众数",
    "moving range": "移动极差",
    "multiplier / normalized linkage": "乘数 / 归一化连接",
    "noise (-1)": "噪声 (-1)",
    "null (E=1)": "零假设 (E=1)",
    "null (RD=0)": "零假设 (RD=0)",
    "null (RR/OR=1)": "零假设 (RR/OR=1)",
    "null G(n,m)": "零假设 G(n,m)",
    "number in system n": "系统中数量 n",
    "number of classes (k)": "类别数 (k)",
    "number of components k": "组件数 k",
    "number of upper order statistics k": "上序统计量数 k",
    "observation index": "观测索引",
    "observed (95% Wilson CI)": "观测值 (95% Wilson CI)",
    "observed L(r) - r": "观测值 L(r) - r",
    "observed count": "观测计数",
    "observed cumulative MTBF": "观测累积 MTBF",
    "odds ratio (log scale, 95% CI)": "赔率比 (log尺度, 95% CI)",
    "optimal Q vs CR": "最优 Q vs CR",
    "optimal order quantity Q*": "最优订货量 Q*",
    "order quantity Q": "订货量 Q",
    "ordered data": "有序数据",
    "ordering cost D/Q*S": "订货成本 D/Q*S",
    "original distance": "原始距离",
    "out of control": "失控",
    "outlier": "异常值",
    "output multiplier": "输出乘数",
    "p = 0.05 threshold": "p = 0.05 阈值",
    "p-value": "p值",
    "partial dependence": "偏依赖",
    "partial fit": "部分拟合",
    "per-category kappa": "每类kappa",
    "percent": "百分比",
    "perfect calibration": "完美校准",
    "permutation importance (mean drop in score)": "排列重要性 (分数平均下降)",
    "player": "玩家",
    "points sorted by k-distance": "按k距离排序的点",
    "points sorted by robust Mahalanobis d^2": "按稳健马氏距离d^2排序的点",
    "polarity (compound, -1..1)": "极性 (化合物, -1..1)",
    "positive": "正",
    "posterior mean smooth": "后验均值平滑",
    "predicted (CV)": "预测值 (CV)",
    "predicted probability": "预测概率",
    "present value": "现值",
    "present value (cost)": "现值 (成本)",
    "propensity (logit)": "倾向性 (logit)",
    "propensity score": "倾向得分",
    "quantile τ": "分位数τ",
    "radius r": "半径r",
    "random (0.5)": "随机 (0.5)",
    "range": "范围",
    "region": "区域",
    "region of significance": "显著性区域",
    "relative risk ratio RRR = exp(coef), log scale": "相对风险比RRR = exp(coef), 对数尺度",
    "required n per group (80% power)": "每组所需n (80%功效)",
    "residuals vs fitted": "残差 vs 拟合值",
    "robust CI": "稳健CI",
    "robust Mahalanobis d^2": "稳健马氏距离d^2",
    "rows": "行",
    "running peak": "运行峰值",
    "samples grouped by cluster": "按簇分组的样本",
    "sampling depth (individuals)": "采样深度 (个体)",
    "seasonal": "季节性",
    "sector": "扇区",
    "segmented fit": "分段拟合",
    "series": "序列",
    "silhouette coefficient": "轮廓系数",
    "silhouette plot": "轮廓图",
    "simulated NPV": "模拟NPV",
    "sites": "站点",
    "slope of X on Y": "X对Y的斜率",
    "smoothed P(regime)": "平滑P(状态)",
    "smoothed level": "平滑水平",
    "smoothed seasonal": "平滑季节性",
    "smoothed trend (slope)": "平滑趋势 (斜率)",
    "source": "源",
    "spatial lag (W·z)": "空间滞后 (W·z)",
    "specific indirect (95% boot CI)": "特定间接 (95% bootstrap CI)",
    "stable-region band": "稳定区域带",
    "standardised loading": "标准化载荷",
    "standardized coefficient": "标准化系数",
    "standardized mean (z)": "标准化均值 (z)",
    "standardized series": "标准化序列",
    "std. residual": "标准残差",
    "survivors l_x": "生存者l_x",
    "target (population)": "目标 (总体)",
    "test (mean ± 1.96σ)": "检验 (均值 ± 1.96σ)",
    "test data": "测试数据",
    "test points (sorted by actual)": "测试点 (按实际值排序)",
    "test points (sorted by prediction)": "测试点 (按预测值排序)",
    "threshold v (loss)": "阈值 v (损失)",
    "total (ordering+holding)": "总计 (排序+持有)",
    "total cost": "总成本",
    "total impact (direct + indirect)": "总影响 (直接 + 间接)",
    "total revenue": "总收入",
    "train data": "训练数据",
    "treated": "已处理",
    "upper-bound p": "上限 p",
    "zero": "零",
    "|series - mean|": "|序列 - 均值|",
}
